### ISSUE TITLE
Map features

### ISSUE THREAD

**Issue by nandomoreirame** [price-format/price-format#1]
This issue is to map features existing in the [jQuery Price Format](https://github.com/price-format/Jquery-Price-Format) and discuss them and create an activity for each.

**Comment by nandomoreirame** [comment]
hey guys, let's kill this issue this week? what is your opinion about thi s idea?

**Comment by nandomoreirame** [comment]
- [ ] #2 Prefix
- [ ] #3 Cents Separator
- [ ] #4 Thousands Separator
- [ ] #5 Suffix
- [ ] #6 When Input, do not allow non number keys
- [ ] #7 Limit
- [ ] #8 Cents Limit
- [ ] #9 Clear Prefix and Suffix on Blur
- [ ] #10 Option to allow Negative
- [ ] #11 Option to show plus sign with the value
- [ ] #12 Option to clear on empty
- [ ] #13 Function UnPrice
- [ ] #14  Function UnMask
- [ ] #15 Function Price to float

**Comment by flaviosilveira** [comment]
Ok guys,
I think thats it for now.

I checked some forks but nothing take my attention.
Let me know if you see something and we can add later.
